[project]
name = 'fitness-mining'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.fitness-mining]
path = 'contracts/fitness-mining.clar'
clarity_version = 3
epoch = 3.1

[contracts.social-challenges]
path = 'contracts/social-challenges.clar'
clarity_version = 3
epoch = 3.1

[contracts.challenge-templates]
path = 'contracts/challenge-templates.clar'
clarity_version = 3
epoch = 3.1

[contracts.achievement-badges]
path = 'contracts/achievement-badges.clar'
clarity_version = 3
epoch = 3.1

[contracts.fitness-rentals]
path = 'contracts/fitness-rentals.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
